esphome:
  platform: esp32
  name: pool_pump_controller
  board: esp32dev
 includes:
    - components/flow_rate_sensor/flow_rate_sensor.h  # Include the custom C++ file for the flow sensor
    
ethernet:
  type: W5500
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19
  cs_pin: GPIO33

logger:

api:
  password: "PQLVtmP9qwyFnlWX7W"

ota:
  - platform: esphome
    password: "PQLVtmP9qwyFnlWX7W"

time:
  - platform: homeassistant
    id: homeassistant_time

external_components:
  - source:
      type: git
      url: https://github.com/BShurilla/CenturyVSPump
      ref: main

binary_sensor:
  - platform: gpio
    name: Pool Pump Controller button
    pin:
      inverted: True
      number: GPIO39

button:
  - platform: template
    name: Pool Pump Controller Demand 600RPM
    id: id_button_7
    on_press:
      then:
        - number.set:
            id: id_number_rpm
            value: 600
  - platform: template
    name: Pool Pump Controller Demand 2600RPM
    id: id_button_6
    on_press:
      then:
        - number.set:
            id: id_number_rpm
            value: 2600
  - platform: template
    name: Pool Pump Controller Demand 3450RPM
    id: id_button_8
    on_press:
      then:
        - number.set:
            id: id_number_rpm
            value: 3450

centuryvspump:

light:
  - platform: neopixelbus
    name: Pool Pump Controller LED
    id: id_light_1
    num_leds: 1
    pin: GPIO27
    variant: SK6812

modbus:
  id: id_modbus_3

number:
  - platform: centuryvspump
    name: Pool Pump Controller Demand
    id: id_number_rpm

sensor:
  - platform: centuryvspump
    name: Pool Pump Controller RPM
    type: rpm
    unit_of_measurement: RPM
  - platform: centuryvspump
    name: Pool Pump Controller Demand
    address: 3
    page: 0
    scale: 4
    type: custom
    unit_of_measurement: RPM
  - platform: custom
    lambda: |-
      auto flow_sensor = new FlowRateSensor();
      App.register_component(flow_sensor);
      return {flow_sensor->get_flow_sensor()};
    sensors:
      name: "Flow Rate"
      unit_of_measurement: "GPH"

switch:
  - platform: centuryvspump
    name: Pool Pump Controller Run
    id: id_switch_4

uart:
  id: id_uart_2
  baud_rate: 9600
  debug:
  rx_pin: GPIO3
  tx_pin: GPIO1

web_server:
  local: True
  port: 80
