esphome:
  platform: esp32
  name: century_vs_pump
  board: pico32
  includes:
    - CenturyVSPump.h
    - CenturyVSPump.cpp
  on_boot:
    then:
      light.turn_on:
        id: id_light_1
        blue: 1.0
        brightness: 0.3
        green: 1.0
        red: 1.0
wifi:
  ap:
    password: !secret ap_PWD
    ssid: century_vs_pump
  password: !secret wifi_PWD
  ssid: !secret wifi_SSID
captive_portal:
external_components:
  - source:
      type: git
      url: https://github.com/gazoodle/esphome
      ref: Feature-Request-#1725
    components: [modbus]
logger:
api:
  password: !secret api_PWD
ota:
  password: !secret ota_PWD
time:
  - platform: homeassistant
    id: homeassistant_time
binary_sensor:
  - platform: gpio
    name: Century VS Pump Controller button
    pin:
      inverted: True
      number: GPIO39
button:
  - platform: restart
    name: Century VS Pump Controller Restart
  - platform: template
    name: Century VS Pump Controller 2600RPM
    id: id_button_14
    on_press:
      then:
        - uart.write: [0x15, 0x44, 0x20, 0x00, 0xA0, 0x28, 0x81, 0x0F]
custom_component:
  - lambda: |-
      auto custom_component = new CenturyVSPump(id(id_modbus_3), "Pool Pump", 0x15);
      return {custom_component};
    components:
      id: id_century_vs_pump_13
light:
  - platform: neopixelbus
    name: Century VS Pump Controller led
    id: id_light_1
    num_leds: 1
    pin: GPIO27
    variant: SK6812
modbus:
  id: id_modbus_3
sensor:
switch:
uart:
  id: id_uart_2
  baud_rate: 9600
  rx_pin: GPIO22
  tx_pin: GPIO19
web_server:
  port: 80
